name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    if: |
      ((github.event_name == 'push' && github.repository == 'ThePotato97/PhasmophobiaPotatoGUIPublic') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'ThePotato97/PhasmophobiaPotatoGUIPublic')) && !contains(github.event.head_commit.message, 'skip compile')
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
        token: '${{ secrets.PAT }}'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal      
